package lk.ijse.raillankaprobackend.service.impl;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import lk.ijse.raillankaprobackend.dto.BookingDto;
import lk.ijse.raillankaprobackend.repository.BookingRepository;
import lk.ijse.raillankaprobackend.service.BookingService;
import lk.ijse.raillankaprobackend.service.QRService;
import lombok.RequiredArgsConstructor;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * @author manuthlakdiv
 * @email manuthlakdiv2006.com
 * @project RailLanka Pro - Backend
 * @github https://github.com/ManuthLakdiw
 */

@org.springframework.stereotype.Service
@RequiredArgsConstructor
public class QRServiceImpl implements QRService {
    private final BookingService bookingService;
    private final BookingRepository bookingRepository;


//    @Override
//    public byte[] generateQRCode(String content, int width, int height) {
//        QRCodeWriter qrCodeWriter = new QRCodeWriter();
//        try {
//            BitMatrix bitMatrix = qrCodeWriter.encode(content, BarcodeFormat.QR_CODE,width,height);
//            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
//            MatrixToImageWriter.writeToStream(bitMatrix, "PNG", byteArrayOutputStream);
//            return byteArrayOutputStream.toByteArray();
//        } catch (WriterException e) {
//            throw new RuntimeException(e.getMessage());
//        } catch (IOException e) {
//            throw new RuntimeException(e.getMessage());
//        }
//    }
public byte[] generateBeautifulBookingQR(String bookingId) {
    bookingRepository.findById(bookingId).orElseThrow(
            () -> new RuntimeException("Booking with id " + bookingId + " does not exist"));
    String qrContent = formatBookingContent(bookingId);
    return generateStyledQRCodeWithText(qrContent, 500, 500, "Generated By RailLanka Pro System");
}

    private String formatBookingContent(String bookingId) {
        BookingDto bookingDto = bookingService.getBookingDetailsByBookingId(bookingId);
        return "🚆 RAIL LANKA PRO - BOOKING DETAILS 🚆\n" +
                "====================================\n" +
                "Booking ID: " + bookingDto.getBookingId() + "\n" +
                "Passenger: " + bookingDto.getPayeeInfo().getFirstName() + "\n" +
                "NIC/Passport: " + bookingDto.getPayeeInfo().getNicOrPassport() + "\n" +
                "Route: " + bookingDto.getDepartureStation() + " → " + bookingDto.getDestinationStation() + "\n" +
                "Train: " + bookingDto.getTrainName() + "\n" +
                "Date: " + bookingDto.getFormattedTravelDate() + "\n" +
                "Time: " + bookingDto.getDepartureTime() + " - " + bookingDto.getArrivalTime() + "\n" +
                "Class: " + bookingDto.getTravelClass() + "\n" +
                "Seats: " + bookingDto.getFormatedselectedSeat() + "\n" +
                "Passengers: " + bookingDto.getAdultCount() + " Adult(s), " + bookingDto.getChildCount() + " Child(ren)\n" +
                "Amount: " + bookingDto.getFormattedTotalAmount() + "\n" +
                "====================================";
    }


    private byte[] generateStyledQRCodeWithText(String content, int qrWidth, int qrHeight, String footerText) {
        try {
            int padding = 50;
            int totalHeight = qrHeight + padding + 40;

            BufferedImage combinedImage = new BufferedImage(qrWidth, totalHeight, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = combinedImage.createGraphics();

            g2d.setColor(Color.WHITE);
            g2d.fillRect(0, 0, qrWidth, totalHeight);

            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            Map<EncodeHintType, Object> hints = new HashMap<>();
            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
            hints.put(EncodeHintType.MARGIN, 2);

            QRCodeWriter qrCodeWriter = new QRCodeWriter();
            BitMatrix bitMatrix = qrCodeWriter.encode(content, BarcodeFormat.QR_CODE, qrWidth, qrHeight, hints);

            BufferedImage qrImage = createStyledQRImage(bitMatrix, qrWidth, qrHeight);

            // Draw QR
            g2d.drawImage(qrImage, 0, 0, null);

            // Draw QR
            g2d.drawImage(qrImage, 0, 0, null);

            try {
                BufferedImage logo = ImageIO.read(getClass().getResourceAsStream("/images/rail-lanka-logo.png"));
                int logoSize = qrWidth / 5; // logo size = 1/5 of QR width
                int logoX = (qrWidth - logoSize) / 2;
                int logoY = (qrHeight - logoSize) / 2;

                g2d.setColor(Color.WHITE);
                g2d.fillRoundRect(logoX - 10, logoY - 10, logoSize + 20, logoSize + 20, 20, 20);

                // Draw the logo
                g2d.drawImage(logo, logoX, logoY, logoSize, logoSize, null);
            } catch (IOException e) {
                System.err.println("Logo not found: " + e.getMessage());
            }


            g2d.setColor(new Color(0, 82, 147));
            g2d.setFont(new Font("Arial", Font.BOLD, 16));

            FontMetrics metrics = g2d.getFontMetrics();
            int textWidth = metrics.stringWidth(footerText);
            int x = (qrWidth - textWidth) / 2;
            int y = qrHeight + 30;

            g2d.drawString(footerText, x, y);

            g2d.setStroke(new BasicStroke(2));
            g2d.setColor(new Color(220, 220, 220));
            g2d.drawLine(20, qrHeight + 10, qrWidth - 20, qrHeight + 10);

            g2d.dispose();

            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            ImageIO.write(combinedImage, "PNG", byteArrayOutputStream);
            return byteArrayOutputStream.toByteArray();

        } catch (WriterException | IOException e) {
            throw new RuntimeException("Error generating styled QR code: " + e.getMessage());
        }
    }

    private BufferedImage createStyledQRImage(BitMatrix bitMatrix, int width, int height) {
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics = image.createGraphics();

        graphics.setColor(Color.WHITE);
        graphics.fillRect(0, 0, width, height);

        Color qrColor = new Color(0, 82, 147); // Dark blue
        graphics.setColor(qrColor);

        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                if (bitMatrix.get(x, y)) {
                    graphics.fillRect(x, y, 1, 1);
                }
            }
        }

        graphics.dispose();
        return image;
    }




}
